# PATH (from bash -> zsh)
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ys"

plugins=(git z sudo zsh-autosuggestions zsh-syntax-highlighting)
[[ -f $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh

# Vim-friendly defaults
export EDITOR=vim
export VISUAL=vim
bindkey -v

# ROS Humble
[[ -f /opt/ros/humble/setup.zsh ]] && source /opt/ros/humble/setup.zsh

